name: Derecho Testing

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  pytest:
    runs-on: gha-runner-crocodash
    steps:
      - name: Check /glade access
        run: |
          echo "Listing /glade:"
          ls -ld /glade || echo "/glade not accessible"

          echo
          echo "Attempting to read:"
          ls /glade | head -n 20
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: CrocoDash
      - name: Run Pytest
        run: |
          cd CrocoDash
          source /glade/work/manishrv/conda-envs/CrocoDash_pint/bin/activate
          pytest --ignore=CrocoDash/visualCaseGen -m "not workflow" -vv --capture=no --showlocals --tb=short
