name: Derecho Testing

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  pytest:
    runs-on: gha-runner-crocodash
    container:
      image: ghcr.io/crocodile-cesm/crocodash:nightly
    steps:
      - name: Check /glade access
        run: |
          echo "Listing /glade:"
          ls -ld /glade || echo "/glade not accessible"

          echo
          echo "Attempting to read:"
          ls /glade/campaign/collections/gdex/data/d651077/cesmdata/inputdata/ocn/mom/croc | head -n 20
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: CrocoDash
